const fallbackNews=[{cat:'business',tag:'أعمال AI',title:'وكلاء الذكاء الاصطناعي ينتقلون من التجربة إلى الإنتاج',text:'جيل جديد من وكلاء AI يستطيع تنفيذ سلاسل طويلة من المهام، ما يفتح فرصاً جديدة للشركات والمستقلين.',date:'اليوم',source:'AIProfit'},{cat:'tools',tag:'أدوات AI',title:'أدوات الذكاء الاصطناعي تتخصص بسرعة',text:'البحث والفيديو والتصميم والبرمجة والأتمتة أصبحت مجالات متخصصة. اختر الأداة بناءً على النتيجة التي تريدها.',date:'هذا الأسبوع',source:'AIProfit'},{cat:'agents',tag:'وكلاء AI',title:'لماذا أصبحت أتمتة العمليات فرصة حقيقية؟',text:'حل مشكلة متكررة يدفع الناس أو الشركات مقابل حلها هو نقطة بداية أقوى من مطاردة وعود الربح السريع.',date:'دليل عملي',source:'AIProfit'}];
let news=[...fallbackNews];
const grid=document.querySelector('#news-grid');
function render(filter='all'){if(!grid)return;grid.innerHTML='';news.filter(n=>filter==='all'||n.cat===filter).forEach(n=>{const a=document.createElement('article');a.className='news-card';a.innerHTML='<div class="tag">'+escapeHtml(n.tag||'أخبار AI')+'</div><h3>'+escapeHtml(n.title)+'</h3><p>'+escapeHtml(n.text)+'</p><div class="meta">'+escapeHtml(n.date||'')+' · '+escapeHtml(n.source||'AIProfit')+'</div>'+(n.url?'<a class="read-more" href="'+escapeAttr(n.url)+'" target="_blank" rel="noopener noreferrer">اقرأ الخبر الأصلي ←</a>':'<button class="read-more" type="button">اقرأ التحليل ←</button>');grid.appendChild(a)})}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function escapeAttr(v){return String(v).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
render();
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)}));
fetch('news.json?ts='+Date.now()).then(r=>{if(!r.ok)throw new Error('feed');return r.json()}).then(data=>{if(Array.isArray(data)&&data.length){news=data;render(document.querySelector('.filter.active')?.dataset.filter||'all')}}).catch(()=>{});
function subscribe(e){e.preventDefault();const msg=document.querySelector('#form-msg');if(msg)msg.textContent='✓ تم تسجيل طلبك في النسخة التجريبية.'}
